{% set name = "seer" %}
{% set version = "1.1.4" %}

package:
  name: {{ name|lower}}
  version: {{ version }}

source:
  url: https://github.com/johnlees/{{ name|lower }}/releases/download/v{{ version }}/{{ name|lower }}_v{{ version }}_submodules.tar.gz
  sha256: d83b53b5e16d7aeda003e512890961a36089ad914837be21ce96871bda9a5e4a

build:
  skip: True #  [osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python ==2.7
    - zlib
    - armadillo
    - hdf5
    - lapack
    - openblas
    - pthread-stubs
  run:
    - zlib
    - lapack
    - openblas
    - armadillo
    - hdf5
    - pthread-stubs

test:
  commands:
    - seer --version
    - kmds --version
    - combineKmers -h
    - filter_seer --version

about:
   home: https://github.com/johnlees/seer
   license: GPL-2
   license_family: GPL
   license_file: LICENSE
   summary: sequence element (kmer) enrichment analysis

extra:
   identifiers:
     - doi:10.1038/ncomms12797
