{% set name = "sonicparanoid" %}
{% set version = "1.0.13" %}
{% set commit = "1c9be381b8b7" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://bitbucket.org/salvocos/sonicparanoid/get/{{ commit }}.zip
  sha256: 25b9a4f6b69481bf1054fd3470aa44c37bfbb6c9efe68c4c656a8d01ce1f9974

requirements:
  build:
    - gcc
    - numpy >=1.13.0
    - cython >=0.27.0
  run:
    - pip >=9.0.1
    - cython >=0.27.0
    - sh >=1.12.14
    - setuptools >=24.2.0
    - biopython >=1.67
    - pandas >=0.22.0
    - numpy >=1.13.0
    - python

test:
  commands:
    - "sonicparanoid --help"

about:
  home: "http://iwasakilab.bs.s.u-tokyo.ac.jp/sonicparanoid/"
  license: "GNU General Public License v3"
  license_family: "GPL3"
  summary: "SonicParanoid: fast, easy and accurate orthology inference"
