{% set name = "sonicparanoid" %}
{% set version = "1.0.13" %}
{% set commit = "7730580f357a" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  noarch: python

source:
  url: https://bitbucket.org/salvocos/sonicparanoid/get/{{ commit }}.zip
  sha256: 92ecb356b6a34aed4251340e566905c603b47598aeac851558090b010a8c2faf

requirements:
  build:
    - {{ compiler("cxx") }}
  host:
    - numpy
    - cython
  run:
    - pip >=9.0.1
    - cython >=0.27.0
    - sh >=1.12.14
    - setuptools >=24.2.0
    - biopython >=1.67
    - pandas >=0.22.0
    - numpy >=1.13.0
    - python

test:
  commands:
    - "sonicparanoid"

about:
  home: "http://iwasakilab.bs.s.u-tokyo.ac.jp/sonicparanoid/"
  license: "GNU General Public License v3"
  license_family: "GPL3"
  license_file: "LICENSE.md"
  summary: "SonicParanoid: fast, easy and accurate orthology inference"
