package:
  name: igblast
  version: "1.9.0"

about:
  home: http://www.ncbi.nlm.nih.gov/projects/igblast/
  license: Public Domain
  summary: A tool for analyzing immunoglobulin (IG) and T cell receptor (TR) sequences.

source:
  # Use sources on Linux, binaries on macOS
  sha256: d3e138867fc7eacc9153752dcda69ce3e5db39e103d214d284f625acac001b5e  # [linux]
  sha256: 32a974c944520ffaa8aa4261c9da2d19098cc92056835178d1215edd7539ecee  # [osx]
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.9.0/ncbi-igblast-1.9.0-src.tar.gz  # [linux]
  url: ftp://ftp.ncbi.nih.gov/blast/executables/igblast/release/1.9.0/ncbi-igblast-1.9.0-x64-macosx.tar.gz  # [osx]

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - git
  host:
    - gnu-wget
    - zlib
    - bzip2
    - sqlite
    - libstdcxx-ng
  run:
    - zlib
    - bzip2
    - sqlite
    - libstdcxx-ng
    - perl

test:
  commands:
    - igblastn -h
    - igblastp -h
    - makeblastdb -h

extra:
  identifiers:
    - biotools:igblast
